### ISSUE TITLE
Wrong password and user doesn't exist messages are not very user-friendly

### ISSUE THREAD

**Issue by Kazjon** [naturenet/naturenet-www#10]
While signing in on the website, if you get your email wrong you get a technical sounding error message in the bottom corner of the page, rather than the standard design pattern of a user-friendly error at or near the text entry boxes. Examples:

<img width="1873" alt="screen shot 2016-08-11 at 2 59 55 pm" src="https://cloud.githubusercontent.com/assets/3923214/17601075/60e6081c-5fd4-11e6-8b0e-c537d5ad8c58.png">
<img width="326" alt="screen shot 2016-08-11 at 2 59 38 pm" src="https://cloud.githubusercontent.com/assets/3923214/17601077/6357b1cc-5fd4-11e6-81e1-1fdaba4af710.png">

**Comment by WildWeazel** [comment]
I'm adding the code to insert more user-friendly messages for each case, but we should document the desired wording for each of these to share across clients as much as possible.
