### ISSUE TITLE
Error thrown after clicking "Recent Observations" after logging in

### ISSUE THREAD

**Issue by Kazjon** [naturenet/naturenet-www#11]
After clicking on the top entry in the "Recent Observations" panel on the top right of the home page immediately after logging in, I saw the following error message appear.  I am able to use the page and interact with the content, so it's not clear what this error refers to:

<img width="1366" alt="screen shot 2016-08-11 at 10 11 36 pm" src="https://cloud.githubusercontent.com/assets/3923214/17610899/9bd3227a-6010-11e6-8247-4573e89eb3fa.png">

**Comment by Kazjon** [comment]
Clicking and zooming actually does pop more similar-looking errors -- and the zoom of the map doesn't appear to be right for the one contribution shown by "Lizzie".  Not sure what's going on here.

**Comment by WildWeazel** [comment]
This is a result of the data mismatch between website and old build of iOS. I have a script to fix these in the DB. But falls under the general issue of logging these exceptions and printing something more user-friendly instead.

**Comment by Kazjon** [comment]
Hmm, we should discuss better error presentation in a design meeting.  That's a much bigger issue we should probably all talk about. 

Will the script you're talking about convert all old data and then this particular error will never show up again? Or will people still be submitting new stuff that triggers this?

**Comment by WildWeazel** [comment]
New submissions from 1.6 or earlier will produce this. The script will fix whatever is already submitted.

**Comment by WildWeazel** [comment]
Closing this since it's an app/maintenance issue that will sort itself out as people update but I'll open another one for error messages
