### ISSUE TITLE
Photos no longer clickable + descriptions/comments unreadable when viewed under Projects or Communities

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet-www#115]
Steven notes that the map used to be active on each page but this functionality was removed in new version to greatly speed up load times.

Downsides are inability to get closer look at individual photo and loss of ability to read any descriptions or add comments when in Projects or Communities. For now, this is only possible via Explore.

**Comment by carolboston2** [comment]
Hi, Stephen,

Excited to see this closed: I think it means you've solved it and will push
out an update soon?



Carol

**Comment by stevemacn** [comment]
Yes! All fixed - I knew this was a critical issue so I pushed it directly to the production server. It should be available now (let me know if there is an issue!)
