### ISSUE TITLE
Inconsistent interaction around upvoting and commenting in left pane of Explore

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet-www#117]
In left pane of Explore, clicking on thumb gets you nowhere, but clicking on speech cloud gets the photo to enlarge. 

With the enlarged photo, clicking on thumb gets you nowhere, but clicking on speech cloud opens up the area in which you can click the thumb for real or leave a comment.

It's nonintuitive to have to click two speech clouds to be able to give a thumbs up.
![no thumbs up](https://user-images.githubusercontent.com/21040279/31796046-18ceba38-b4f6-11e7-8455-7c92b888b81b.PNG)

**Comment by carolboston2** [comment]
Noting that thumb and speech cloud work as expected in Design Ideas area, so hope the fix might be easy!

**Comment by stevemacn** [comment]
Not only an issue for "Explore" page but also for some of the modals. To fix: liking functionality should be moved to a service handled directly by the nn-social widget. Improves maintainability and provides consistent behavior.
