### ISSUE TITLE
Comment saved in app did not appear on website

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet-www#14]
1. Went to Explore on iOS app, zoomed in to photo near my current location in MD.
2. Selected Lizzie/Aug 11/Comm garden with veggies & flowers and wrote comment: Is that near Epply?
3. Saw Alert: Comment Posted Successfully.
4. No comment appeared on website.

However, tried it with a second picture in Explore on iOS app and the comment DID save. 
1. Went to Explore, zoomed into photo from YRE/Aug 10/Cardinal flowers
2. Wrote: Did not know their name.
3. Saw Alert: Comment Posted Successfully
4. Comment DID appear on website. Here is a clue about what might be the issue: on the website, when I click on the picture, under user name YRE on right side, I saw name of  Project (Tracks); under Lizzie, I saw NO project name.

**Comment by WildWeazel** [comment]
This should be addressed by https://github.com/naturenet/naturenet_ios/issues/15 in the next build. Database maintenance will take care of existing cases.
