### ISSUE TITLE
Map goes black when an observation is clicked

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-www#17]
When I click on explore and then click on one of the images in the left bar, the map goes black.  It only happens with the last three posts by Travis.  I have to refresh the webpage or click on someone else's observation to get the map to come back.  

![screen shot 2016-08-21 at 12 13 33 pm](https://cloud.githubusercontent.com/assets/4220521/17839017/116b658a-6799-11e6-972e-4ef943bb8858.png)

**Comment by cameronjj** [comment]
Also happens if I click on Travis' observations from the homepage.

**Comment by cameronjj** [comment]
Akash's also got the black map when I clicked on this observation: 

![screen shot 2016-08-21 at 12 34 31 pm](https://cloud.githubusercontent.com/assets/4220521/17839112/accf073c-679b-11e6-8c45-b725c9e48801.png)

**Comment by WildWeazel** [comment]
This is the "coast of Africa" issue and is the app's fault, though maybe the website should have a special case for this since we don't cater to Ghanan sea vessels

**Comment by Kazjon** [comment]
It looks like this happens when an observation is in a place where Google Maps doesn't have high-res maps.  We try to zoom in further than they have image assets to support, so we get the "Sorry, no Ghanan fishing traffic" message.

**Comment by Kazjon** [comment]
I believe fixing this could be done through fixing #12 (zooming less could stop this happening without us needing a special case)

**Comment by WildWeazel** [comment]
This would be helpful: it tells you the maximum zoom level of imagery at a given location
https://developers.google.com/maps/documentation/javascript/maxzoom

**Comment by WildWeazel** [comment]
This particular case wasn't directly addressed, but due to cumulative changes in the apps you shouldn't see it anymore. If location data isn't available at all it defaults to the user's home site.
