### ISSUE TITLE
Like / dislike remain highlighted even when removed

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-www#19]
When I click on a like (or dislike) icon and then click again, it remains highlighted in color.  Happens in the popup windows for observations and design ideas.

![screen shot 2016-08-21 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/4220521/17839063/64f4e054-679a-11e6-9624-4450ce61c04a.png)

**Comment by WildWeazel** [comment]
This does not happen on your own contributions, oddly enough

**Comment by WildWeazel** [comment]
Nope, false attribution- it's when you remove the _only_ like/dislike. Found the bug.
