### ISSUE TITLE
Disappearing Join NatureNet Today Button

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-www#21]
When I first get to the website, the join button isn't there.  But if I click on another page and then back to the main page (either by back button or logo), it shows up.

![screen shot 2016-08-21 at 12 37 57 pm](https://cloud.githubusercontent.com/assets/4220521/17839130/4d0dbd9c-679c-11e6-80fa-171ef22cbcb4.png)
![screen shot 2016-08-21 at 12 37 51 pm](https://cloud.githubusercontent.com/assets/4220521/17839131/4e8f3a10-679c-11e6-91fb-aed460cf2055.png)

**Comment by WildWeazel** [comment]
This might not even be there after the home page redesign, but there is a bug in the way session changes are propagated which might have other side effects

**Comment by WildWeazel** [comment]
The button isn't on the page at the moment but the underlying issue is fixed
