### ISSUE TITLE
Home page images don't link to pages (website)

### ISSUE THREAD

**Issue by cschneck** [naturenet/naturenet-www#34]
Issue: Main page links
Type: Website (computer, chrome)
Error: Usability, not bug

The home page includes the header icons, but also the main page images seen below. 

However, only the header icons can be clicked to navigate the site. But since the images below also include the same words as the header icons, I assume that either could be pressed to navigate to the same place. Since I wasn't able to, this can make the UI confusing for first-time users.

It would be helpful if these images were able to link as well since it is what people looking at the website for the first time will see. When I started on the webpage I want to start to explore. Since the images below the header are the largest I went to click these before looking to click on the header. Perhaps since this part of the page isn't being used, it can be removed and you could include more general images or information about how to use this website and what is it for. 

![image](https://cloud.githubusercontent.com/assets/22159116/19843317/ccd0b508-9ee6-11e6-8176-ddb220ba0593.png)

**Comment by WildWeazel** [comment]
#54
