### ISSUE TITLE
Confusing locations or too little information

### ISSUE THREAD

**Issue by chke6852** [naturenet/naturenet-www#35]
Issue: Project images are not very descriptive or are in confusing locations
Type: Website (computer, chrome)
Error: Usability

When exploring, sometimes clicking on a project will zoom in so far it is difficult to see where you are at, especially on satellite mode. Particularly since there is no way to zoom out all the way or to find the project you may have been browsing previously. This particular project (as seen in screenshot below) doesn't make sense. The only description is "Shrubbery" and it apparently is located in the middle of the ocean off the coast of Africa. Also, there are other photos/projects in the exact same location (found on the bar in the left hand side) of flowers that are clearly located on land but their images lie in the ocean. They are only able to be found in the bar as clicking on the green pin takes you back to the "Shrubbery" picture. It doesn't make sense for the flowers to be there and the "shrubbery" description doesn't tell me really what I'm looking at or even if it actually came from that location at all (the middle of the ocean).

![naturenet1](https://cloud.githubusercontent.com/assets/17206789/19873339/155108f8-9f84-11e6-81db-423625211051.png)

![naturenet2](https://cloud.githubusercontent.com/assets/17206789/19873340/1b047a1e-9f84-11e6-882c-0548dd94f608.png)

It would be useful to ask users for a bit more details when describing their project or image. It may be a bug that some images are in the wrong place. The images are also not able to be looked at in a zoomed form so they are stuck in the smaller format of the project bar.

**Comment by WildWeazel** [comment]
#48
