### ISSUE TITLE
Web page scaling can obfuscate some options in the top menu

### ISSUE THREAD

**Issue by ameletyan** [naturenet/naturenet-www#36]
Below is the issue I am referring to:
![issue1_10 31 2016](https://cloud.githubusercontent.com/assets/8726530/19873594/8b8ef43e-9f85-11e6-932d-4fa809687fb2.PNG)

The "Join" option and the "Design Ideas" option are overlapped.

I found this issue when I opened up the page on a browser (Google Chrome) and snapped the window to the right of my screen.  It was at half width as a result.  I was not logged in at the time.

Here is a related issue:
![issue2_10 31 2016](https://cloud.githubusercontent.com/assets/8726530/19873672/f5ec513c-9f85-11e6-8c55-733502abde5d.PNG)

The profile picture appears over the "Design Ideas" highlighting.

Though it does not detract from usability, it may not be what is intended.  I encountered this in the same way as the one above except I was logged in this time.

Both of these issues were on the home page.  I was running Windows 7 Ultimate at the time that I encountered them.

**Comment by WildWeazel** [comment]
#37
