### ISSUE TITLE
Needs to use bootstrap.

### ISSUE THREAD

**Issue by Nolawee** [naturenet/naturenet-www#37]
![screen shot 2016-10-31 at 5 45 57 pm](https://cloud.githubusercontent.com/assets/8075213/19875403/17998820-9f92-11e6-86fc-a896533bec8d.png)
When checking to see if the website is responsive, the ui elements don't adjust correctly to the page. This becomes an issue when trying to work with mobile devices, tablets or anything with smaller screens.

**Comment by WildWeazel** [comment]
yes indeed

**Comment by stevemacn** [comment]
Fixed in #d5e4bdf

**Comment by stevemacn** [comment]
Closed in d5e4bdf42805308c20450e831c12bf857f56123f
