### ISSUE TITLE
Full Window Mode - images

### ISSUE THREAD

**Issue by kabo2956** [naturenet/naturenet-www#38]
Issue: Would like to be able to access full screen mode when looking at an image.
![screen shot 2016-10-31 at 7 23 09 pm](https://cloud.githubusercontent.com/assets/18538677/19877061/513f1ec8-9fa1-11e6-8fbe-daa1ff86c47c.png)

While browsing Naturenet using google chrome on my desktop at home I ran into an issue where I wanted to blow up an image to see finer detail. I immediately clicked on the image in hopes it would blow up to fill the entire window or at least most. Other websites have created a mental mapping telling users they can click images to blow them up, I believe this feature is important for users, especially those using this specific website.
As a side note, I also believe it would be beneficial for the map to zoom out after you are done looking at a specific image just as the map auto-zooms when you click on an image.

**Comment by WildWeazel** [comment]
this was a bug, fixed in a029c10306d62b1e3f9192ea32bf9ac123f6440f
