### ISSUE TITLE
Non-full size window creates problems

### ISSUE THREAD

**Issue by DrewMeyersCUboulder** [naturenet/naturenet-www#40]
When the browsing window size is decreased from full size to half size, functions begin to overlap. For example, the profile link and the top bar containing explore, communities, projects, and design ideas buttons overlap and reduce the functionality of the site. I was using Google chrome on Ubuntu 16.04 when I encountered this problem.

![screenshot from 2016-10-31 20-04-27](https://cloud.githubusercontent.com/assets/13531167/19877499/51858288-9fa5-11e6-9688-9fd95a3b23ff.png)

**Comment by WildWeazel** [comment]
#37
