### ISSUE TITLE
Alignment of icons on comments

### ISSUE THREAD

**Issue by dejo7374** [naturenet/naturenet-www#41]
I noticed some misalignment of icons on certain comments. Not sure if it's a widespread issue. I highlighted an example in the attached screenshot.

![example](https://cloud.githubusercontent.com/assets/11949500/19877893/d51cafa6-9fa8-11e6-8ca3-672d050301de.jpg)

**Comment by WildWeazel** [comment]
probably part of #37

**Comment by WildWeazel** [comment]
fixed in 4488b2a15e99691ab460cb24c4ba97bbda4153f0
