### ISSUE TITLE
Text Wrap Readability

### ISSUE THREAD

**Issue by BryceDWilson** [naturenet/naturenet-www#42]
In the list of observations on the left side of the map, if a username is too long, it will put itself on a new line to fit. This causes some text to overlap the comment/like icons. There could be a maximum username length, font size could be scaled down or dynamic, or the size of the box could change based on whether this wrapping occurs.
![capture](https://cloud.githubusercontent.com/assets/21189478/19878969/0230ba68-9fb4-11e6-963c-dd110235bee0.PNG)

**Comment by WildWeazel** [comment]
#41
