### ISSUE TITLE
Clicking on users or photos without location info zooms in on middle of the ocean

### ISSUE THREAD

**Issue by deho9147** [naturenet/naturenet-www#43]
The users with the little green or gray person icons have location info while users without an icon don't have location info.  If you click the users without these icons or the photos they submit you are taken to what i assume is (0,0) on the map.  This transition is jarring and confusing for new users as they are given information which makes no sense rapidly. Instead, a better solution may be to have a warning stating no geographic coordinates as well as leaving the map in the same position as before the click. Another solution may simply be to require users to always have geographic info to post a photo. 

![image](https://cloud.githubusercontent.com/assets/18505844/19879624/51e47878-9fba-11e6-8606-1b13db3b1346.png)

**Comment by WildWeazel** [comment]
#48
