### ISSUE TITLE
Map not complete

### ISSUE THREAD

**Issue by shanesarnac** [naturenet/naturenet-www#44]
When on the website (after making an account), I clicked on the "Explore" tab, which guided me to a map. I decided to go all over the planet and look at all of the areas where a green pin is shown. When I got to Africa, I noticed that the pin appears to be in the ocean South of Ghana. When I tried to zoom in, the screen appeared as shown below. I believe it was likely an island, but there is no way to check and the image associated with the green pin doesn't give any location information in a text-version. To solve this, it would be good to include more specific location information with each green pin to make sure there was no error with the information upload. 

![map-zoom-near-africa](https://cloud.githubusercontent.com/assets/8726636/19880115/d509912a-9fbf-11e6-8a43-3f3486425df2.png)

**Comment by WildWeazel** [comment]
#48
