### ISSUE TITLE
Overlap of Links When Shrinking Page

### ISSUE THREAD

**Issue by abrande** [naturenet/naturenet-www#45]
The page's main links overlap as the screen becomes smaller. The problem occurs when the screen passes 995px on my 15'' laptop.  I was on Google Chrome when I encountered this error. 

<img width="697" alt="screenshot 2016-11-01 01 03 58" src="https://cloud.githubusercontent.com/assets/17368376/19881880/20b3a016-9fcf-11e6-9896-8bd3162116cd.png">

**Comment by WildWeazel** [comment]
#37
