### ISSUE TITLE
General Map Issues

### ISSUE THREAD

**Issue by lale5102** [naturenet/naturenet-www#47]
This screenshot displays all the issues I was having or potential resolutions to better the website. The first issue, within the community tab the images is not displaying properly. I am unsure as to how to solve this issue but was one that I did notice. The second was the issue with the pointer on the map. If it could change it's icon once hovered over the green or icons on the bottom right. It would just easier for users to know that's a clickable area that will not trigger the map itself. 

![issue](https://cloud.githubusercontent.com/assets/12074743/19976943/63d663ee-a1b7-11e6-9901-29f200251650.png)

**Comment by WildWeazel** [comment]
#48
