### ISSUE TITLE
allow users to upload photos to web site from their camera

### ISSUE THREAD

**Issue by maryloumaher** [naturenet/naturenet-www#57]
Many people prefer to use their own camera and not the app. We should add an option to contribute as a new item on the menu bar that goes to a page that allows uploads from a camera as well as a pointer to the mobile apps.

**Comment by WildWeazel** [comment]
related to #30 
need a design for what this page should look like

**Comment by WildWeazel** [comment]
added in the latest deployment

**Comment by maryloumaher** [comment]
great - thanks. I will try this feature later this week.

-------------------------------------------------------------------------
Professor Mary Lou Maher
Chair, Software Information Systems
Director, Center for Education Innovation
Woodward 310A, UNC Charlotte
9201 University City Blvd. | Charlotte, NC 28223
Phone: 704-687-1940| Fax: 704-687-6065
http://sis.uncc.edu/maher-marylou
------------------------------------------------------------------------
