### ISSUE TITLE
Allow users to specify coordinates other than the phone's current location

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-www#67]
Design idea by zaumick on 2016-10-31:

"I think you should be able to adjust the location of where the pictures was taken rather than on cell phone location. What if they took the picture when they didnt have service, and then uploaded the photo when they got home. This could potentially be a security risk say if someone famous uploaded while they were home, we would know their exact location (POTUS)"

**Comment by WildWeazel** [comment]
One way I've seen this done is by opening a new map with a crosshair to drag to the location. Also can use Google Places(?) API to do reverse address lookups if they're at a known landmark/address.

iNaturalist also allows a geoprivacy setting which rounds or fuzzes the exact GPS coordinate.

**Comment by stevemacn** [comment]
Same as #87 and fixed already
