### ISSUE TITLE
Explore search field

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-www#69]
Design idea by Jbarre34 on 2016-10-31:

"I think there needs to be a search bar to navigate through the growing list of pictures within the 'Explore' part of the website. This feature would enable users to search for certain pictures based on contents or who posted it."

**Comment by WildWeazel** [comment]
By searching on multiple fields this is getting into the advanced filtering cases. Firebase Functions should make this easier for us since we can integrate ElasticSearch or other backend search mechanism instead of only working on the client-side data set.

**Comment by stevemacn** [comment]
Feature has been completed for all pages
