### ISSUE TITLE
Map markers do not always appear when snapping to the selected observation

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet-www#75]
When selecting an observation from the sidebar that is outside the map's field of view, no markers are loaded when the map snaps to center on the selected observation. May be because of rounding at a high zoom level, or because the map bounds are changing programmatically. Try lowering zoom level, check that map idle event is called when an observation is selected, or call manually when the selection is made as needed.

**Comment by stevemacn** [comment]
Fixed in 11ac366f1f9e0b0ebef36988a52f634974f4cf5f
