### ISSUE TITLE
Adding vetted, clickable Internet links to project descriptions & posts

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet-www#81]
Still trying to figure out a way to make watershedinfo.umd.edu appear as a clickable link. Right now, it is not even possible to hover over and copy-paste the link.

![capstone snip](https://user-images.githubusercontent.com/21040279/30975292-f6bd7b94-a43f-11e7-991a-123cc7272e58.PNG)

![post snip](https://user-images.githubusercontent.com/21040279/30975430-44e611be-a440-11e7-9c28-39002024162c.PNG)

**Comment by stevemacn** [comment]
Hi @carolboston2 - this is definitely something I'm still looking into. I haven't found a good way to handle it yet. I'll keep you posted as I look into it.

**Comment by carolboston2** [comment]
Thanks!

**Comment by stevemacn** [comment]
Hi @carolboston2! I'm happy to report this is fixed in the upcoming release.
