### ISSUE TITLE
Close button for design idea details pop-up is not very visible or well-located

### ISSUE THREAD

**Issue by Kazjon** [naturenet/naturenet-www#9]
<img width="1875" alt="screen shot 2016-08-11 at 2 56 14 pm" src="https://cloud.githubusercontent.com/assets/3923214/17600970/e66e2358-5fd3-11e6-9d7a-3276cb6c0807.png">

It should be A) on the top right hand corner of the pop-up, and B) not so faint.

**Comment by WildWeazel** [comment]
Agreed. This is per the design mockup, but it should probably match all of the other close buttons.

**Comment by Kazjon** [comment]
Agreed.  Let's fix it to the same close button as appears on the left panel when you click on an individual observation in Explore.

However, there's some kind of "Discussing" thing that appears where that close button would normally go on newly submitted design ideas.  It actually confused me at first, since at-a-glance it looks like a close button.  What's that, what's it mean, and where should we move it to once we put the close button there instead?

**Comment by WildWeazel** [comment]
"Discussing" is the status of the idea, which defaults to Discussing and may change to in progress and/or completed (names TBD) if we decide to implement them. It looks like iOS is not including the correct value here- though really we should assume Discussing as the default case.

**Comment by Kazjon** [comment]
Fair enough, although I would like to initiate a design review of how that is being indicated -- it's really big, it's in a strange place, and it's not well explained.

**Comment by Kazjon** [comment]
I've created a new issue (#16) to discuss the redesign of the status indicators.  Once that's resolved we can move the close button to where it should be and then close this!
