### ISSUE TITLE
Project gallery organization problem

### ISSUE THREAD

**Issue by sabdella** [naturenet/naturenet-www#98]
The pictures listed under the projects are not lined up. It might be related to the difference of avatar's sizes. 
<img width="1440" alt="screen shot 2017-10-05 at 2 11 42 pm" src="https://user-images.githubusercontent.com/21246581/31243174-6d3f861c-a9d7-11e7-914b-9f87b71c44e4.png">

**Comment by stevemacn** [comment]
Same as #83
